/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './router/__root'

// Create Virtual Routes

const SignInLazyImport = createFileRoute('/sign-in')()
const IngredientsLazyImport = createFileRoute('/ingredients')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SignInLazyRoute = SignInLazyImport.update({
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./router/sign-in.lazy').then((d) => d.Route))

const IngredientsLazyRoute = IngredientsLazyImport.update({
  path: '/ingredients',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./router/ingredients.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./router/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/ingredients': {
      preLoaderRoute: typeof IngredientsLazyImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      preLoaderRoute: typeof SignInLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  IngredientsLazyRoute,
  SignInLazyRoute,
])

/* prettier-ignore-end */
