/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './router/__root'
import { Route as SignInImport } from './router/sign-in'
import { Route as AuthImport } from './router/_auth'
import { Route as AuthIndexImport } from './router/_auth.index'

// Create Virtual Routes

const AuthIngredientsLazyImport = createFileRoute('/_auth/ingredients')()
const AuthIngredientsAddLazyImport = createFileRoute('/_auth/ingredients/add')()

// Create/Update Routes

const SignInRoute = SignInImport.update({
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthIngredientsLazyRoute = AuthIngredientsLazyImport.update({
  path: '/ingredients',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./router/_auth.ingredients.lazy').then((d) => d.Route),
)

const AuthIngredientsAddLazyRoute = AuthIngredientsAddLazyImport.update({
  path: '/ingredients/add',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./router/_auth.ingredients_.add.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/_auth/ingredients': {
      preLoaderRoute: typeof AuthIngredientsLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/': {
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/ingredients/add': {
      preLoaderRoute: typeof AuthIngredientsAddLazyImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthRoute.addChildren([
    AuthIngredientsLazyRoute,
    AuthIndexRoute,
    AuthIngredientsAddLazyRoute,
  ]),
  SignInRoute,
])

/* prettier-ignore-end */
